name: Node.js and MongoDB Testing Workflow

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21' 

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: '5.0'

    - name: Install Dependencies
      run: npm install

    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        start: npm run start:test
        wait-on: http://localhost:3030 

    - name: Run Lint
      run: npm run lint

    - name: Run Test Unit
      run: npm run test:unit
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.MYAWSACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.MYAWSSECRET_KEY }}
        aws-region: eu-west-2 

    - name: Zip build directory
      run: zip -r app.zip . -x "node_modules" -x ".*"

    - name: Upload to S3 
      run: aws s3 cp app.zip s3://yusabs-moli

    - name: Create CodeDeploy Application Revision
      run: |
          aws deploy create-deployment \
          --application-name yusabmoli-acebook \
          --s3-location bucket=yusabs-moli,bundleType=zip,key=app.zip \
          --deployment-group-name ysml-production \
          --description "CommitSHA-${{ github.sha }}"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.MYAWSACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.MYAWSSECRET_KEY }}
        AWS_REGION: eu-west-2
      