name: Node.js and MongoDB Testing Workflow

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21' 

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: '5.0'

    - name: Install Dependencies
      run: npm install

    - name: Start server
      run: npm run start:test

    - name: Run Lint
      run: npm lint

    - name: Run Test Unit
      run: npm test:unit

    - name: Run Test Integration
      run: npm test:integration